# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-26 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('ip', models.CharField(max_length=128)),
                ('adminID', models.CharField(max_length=128)),
                ('adminPW', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='serverInfo',
        ),
    ]
